name: Notify on sui.yaml change
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check file change
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q 'crates/sui-core/tests/staged/sui.yaml'; then
            curl -X POST -H 'Content-type: application/json' \
              --data '{"text":"sui.yaml was updated!"}' \
              ${{ secrets.SLACK_WEBHOOK }}
          fi
