name: Sync Fork & Check sui.yaml Changes

on:
  workflow_dispatch:
    inputs:
      test_mode:
        description: "Enable fake upstream change for testing?"
        required: false
        default: "false"
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  sync-and-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Prepare upstream remote
        run: |
          git remote remove upstream || true
          git remote add upstream https://github.com/MystenLabs/sui.git
          git fetch upstream main

      - name: Merge upstream into fork
        run: |
          git merge --no-edit upstream/main || echo "No merge needed"

      - name: "[TEST MODE] Fake change to sui.yaml"
        if: ${{ github.event.inputs.test_mode == 'true' }}
        run: |
          echo "//test-change $(date)" >> crates/sui-core/tests/staged/sui.yaml
          git add crates/sui-core/tests/staged/sui.yaml
          git commit -m "Fake change for testing Slack alert" || echo "No local modifications to commit"

      - name: Check if sui.yaml changed in last commit
        run: |
          echo "Comparing changes from last commit..."
          if git diff --name-only HEAD^ HEAD | grep -q '^crates/sui-core/tests/staged/sui.yaml$'; then
            commit_hash=$(git log -1 --pretty=format:'%h')
            commit_author=$(git log -1 --pretty=format:'%an')
            commit_msg=$(git log -1 --pretty=format:'%s')
      
            # List ID tag
            slack_mentions="<@U096HQGCCBV> <@U789XYZ000> <@U456DEF789>"
      
            echo "✅ sui.yaml was updated — sending Slack alert"
            curl -X POST -H 'Content-type: application/json' \
              --data "{\"text\":\"🚨 sui.yaml was updated in commit ${commit_hash} by ${commit_author}\nMessage: ${commit_msg}\n${slack_mentions}\"}" \
              ${{ secrets.SLACK_WEBHOOK }}
          else
            echo "ℹ️ No changes to sui.yaml"
          fi

      - name: Push changes back to fork
        run: |
          git push origin HEAD:main
